message: This is a message defined in the configuration file config.yaml.
messageRepetitions: 3
database:
   driverClass: com.mysql.jdbc.Driver
   user: root
   password: root
   url: jdbc:mysql://localhost:3306/phonebook
